hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/mph25
hibernate.connection.username=root
hibernate.connection.password=root@39
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=create
hibernate.show_sql=true

#Ehcache configuration

hibernate.cache.use_second-level-cache=true
hibernate.cache.region.factoryclass=org.hibernate.cache.ehcache.EhcacheRegionFactory
